[build-system]
requires = [
  'setuptools==65.6.3',
  'wheel==0.38.4',
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 119
target-version = [
  'py310',
  'py311',
]

[tool.isort]
profile = 'black'
line_length = 119
skip_gitignore = true
